In [28]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.sparse as sp
import scipy.sparse.linalg
import time


# Размеры области
xmin, xmax = 0.0, 1.0
ymin, ymax = 0.0, 1.0

# Точное решение


def u_exact(x, y):
    return np.sin(7.0*x - 3.0*y) + 2.0*np.cos(2.0*x + 6.0*y)

In [29]:
# Define Delta Dirac Function
MEAN = 0
SIGMA = 1e-6


def dirac_delta_approx(x, mean=MEAN, sigma=SIGMA):
    return 1 / (np.sqrt(2 * np.pi) * sigma) * np.exp(-(x-mean)**2 / (2 * sigma**2))


def dirac_delta_ring(x, y, x0=xmax*0.5, y0=ymax*0.5, r0=np.min(xmax, ymax)*0.25):
    return dirac_delta_approx((x-x0)**2 + (y-y0)**2 - r0**2)


# Plot dirac ring function
x = np.linspace(-0.01, 0.01, 100)
y = np.linspace(-0.01, 0.01, 100)
x, y = np.meshgrid(x, y)
delta = dirac_delta_ring(x, y, 0, 0, 0.005)

plt.contourf(x, y, delta, cmap='viridis', levels=100)
plt.title('Representation of Dirac Delta Ring Function with narrow Gaussian')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.colorbar()
plt.show()

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# Неоднородность в уравнении
ro = 1
g = 9.8
M = 0.000001


def f(x, y):
    return ro * g + M * g / 2 / np.pi * dirac_delta_ring(x, y)

# Граничные условия


def phi_L(y):
    return 0


def phi_R(y):
    return 0


def phi_B(x):
    return 0


def phi_T(x):
    return 0

In [ ]:
# Характерное разбиение
h0 = 0.002
lx = xmax - xmin
ly = ymax - ymin

nx = int(np.round(lx / h0)) + 1
ny = int(np.round(ly / h0)) + 1

beg_1 = time.time()

# Узлы сетки
x, hx = np.linspace(xmin, xmax, nx, retstep=True)
y, hy = np.linspace(ymin, ymax, ny, retstep=True)
X, Y = np.meshgrid(x, y, indexing='ij')

N = np.arange(0, X.size, dtype=int).reshape((nx, ny))
print(N)
print(N.shape)

[[     0      1      2 ...    498    499    500]
 [   501    502    503 ...    999   1000   1001]
 [  1002   1003   1004 ...   1500   1501   1502]
 ...
 [249498 249499 249500 ... 249996 249997 249998]
 [249999 250000 250001 ... 250497 250498 250499]
 [250500 250501 250502 ... 250998 250999 251000]]
