$$
u(x,y) = 5(-2x+3y)cos(3x+2y)+3y^2\\
0 \leq x \leq 1,\\
0 \leq y \leq 1\\
$$

$$
u_{xx} = 45 (2 x - 3 y) cos(3 x + 2 y) + 60 sin(3 x + 2 y)\\
u_{yy} = 6 + 20 (2 x - 3 y) cos(3 x + 2 y) - 60 sin(3 x + 2 y)\\
f(x,y) = u_{xx} + u_{yy} = 6 + 65 (2 x - 3 y) cos(3 x + 2 y)\\
$$

_Boundaries:_

$$
\begin{cases}
-u_y(0, y) = \phi_B(y) = -15 cos(2 y) + 6 y (-1 + 5 sin(2 y))
\\
u_y(1, y) = \phi_T(y) = 6 y + 15 cos(3 + 2 y) + (20 - 30 y) sin(3 + 2 y)
\\
-u_x(x, 0) = \phi_L(x) = 10 (cos(3 x) - 3 x sin(3 x))
\\
u_x(x, 1) = \phi_R(x) = -10 cos(2 + 3 x) + 15 (-3 + 2 x) sin(2 + 3 x)
\end{cases}
$$


In [1]:
import numpy as np
from scipy.integrate import dblquad
import sympy as sp
import matplotlib.pyplot as plt
import math

In [2]:
def sol(x, y):
    return 5*(-2*x+3*y)*np.cos(3*x+2*y)+3*y**2


def f(x, y):
    return 6 + 65*(2*x - 3*y)*np.cos(3*x + 2*y)


def phi_B(y):
    return -15*np.cos(2*y) + 6*y*(-1 + 5*np.sin(2*y))


def phi_T(y):
    return 6*y + 15*np.cos(3 + 2*y) + (20 - 30*y)*np.sin(3 + 2*y)


def phi_L(x):
    return 10*(np.cos(3*x) - 3*x*np.sin(3*x))


def phi_R(x):
    return -10*np.cos(2 + 3*x) + 15*(-3 + 2*x)*np.sin(2 + 3*x)


xmax = 1
ymax = 1
xmin = 0
ymin = 0

dx = 0.1
dy = 0.1

x = np.arange(xmin, xmax + dx, dx)
y = np.arange(ymin, ymax + dy, dy)
print(len(x))

# Matrix for Finite Volumn Method
A = np.zeros(((len(x)-1) * (len(y)-1), (len(x)-1) * (len(y)-1)))
A.shape

11


(100, 100)

In [3]:
class Cell:
    def __init__(self, P, E, W, N, S):
        self.P = P
        self.E = E
        self.W = W
        self.N = N
        self.S = S

    def __repr__(self) -> str:
        return f"(P: {self.P:.2e}, E: {self.E:.2e}, W: {self.W:.2e}, N: {self.N:.2e}, S: {self.S:.2e})"

In [4]:
def get_pos(n, i, j):
    return n * (i - 1) + j - 1


def create_matrix(xmin, ymin, xmax, ymax, dx, dy, f, phi_B, phi_L, phi_R, phi_T):
    x = np.arange(xmin, xmax + dx, dx)
    y = np.arange(ymin, ymax + dy, dy)
    n = len(x) - 1  # minus 1 because we are considering cells, not points
    A = np.zeros(((len(x)-1) * (len(y)-1), (len(x)-1) * (len(y)-1)))
    B = np.zeros((len(x)-1) * (len(y)-1))
    for i in range(1, n+1):
        for j in range(1, n+1):
            B[get_pos(n, i, j)] = dblquad(
                f, x[i-1], x[i-1]+dx, y[j-1], y[j-1]+dy)[0]

    for i in range(n**2-n):
        A[i, i+n] = dx/dy
        A[i+n, i] = dx/dy

    # first row
    A[0, 0] = A[n-1, n-1] = -dy/dx - dx/dy
    B[0] += -dy*phi_L(x[0]+dx/2) - dx*phi_B(y[0]+dy/2)
    B[n-1] += -dy*phi_R(x[n]+dx/2) - dx*phi_B(y[0]+dy/2)
    for i in range(n-1):
        if i > 0:
            A[i, i] = -2*dy/dx - dx/dy
            B[i] += -dx*phi_B(y[0]+dy/2)
        A[i+1, i] = A[i, i+1] = dy/dx

    # middle rows
    for i in range(2, n):
        first_cell_pos = get_pos(n, i, 1)
        last_cell_pos = get_pos(n, i, n)
        B[first_cell_pos] += -dy*phi_L(x[0]+dx/2)
        B[last_cell_pos] += -dy*phi_R(x[n]+dx/2)
        A[first_cell_pos, first_cell_pos] = A[last_cell_pos,
                                              last_cell_pos] = -dy/dx - 2*dx/dy
        for j in range(first_cell_pos, last_cell_pos):
            if j > first_cell_pos:
                A[j, j] = -2*(dx/dy+dy/dx)
            A[j+1, j] = A[j, j+1] = dy/dx

    # last row
    B[get_pos(n, n, 1)] += -dx*phi_T(y[n]+dy/2) - dy*phi_L(x[0]+dx/2)
    B[get_pos(n, n, n)] += -dx*phi_T(y[n]+dy/2) - dy*phi_R(x[n]+dx/2)
    A[n*(n-1), n*(n-1)] = A[n**2-1, n**2-1] = -dy/dx - dx/dy
    for i in range(n*(n-1), n*n-1):
        if i > n*(n-1):
            A[i, i] = -2*dy/dx - dx/dy
            B[i] += dx*phi_T(y[n]+dy/2)
        A[i+1, i] = A[i, i+1] = dy/dx
    return A, B

In [5]:
A, B = create_matrix(xmin, ymin, xmax, ymax, dx, dy,
                     f, phi_B, phi_L, phi_R, phi_T)
np.savetxt('matrix_A1.txt', A, fmt='%.1f')
np.savetxt('matrix_B1.txt', B, fmt='%.2f')
print(A)
print(B)

[[-2.  1.  0. ...  0.  0.  0.]
 [ 1. -3.  1. ...  0.  0.  0.]
 [ 0.  1. -3. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -3.  1.  0.]
 [ 0.  0.  0. ...  1. -3.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]]
[ 0.56985577  1.65020166  1.71686377  1.71277366  1.62595611  1.45805659
  1.22473997  0.95423171  0.68413692 -0.34212757 -1.11010095 -0.01095589
  0.0760813   0.09539358  0.03697954 -0.0955585  -0.28519201 -0.50345084
 -0.71399643 -1.67638043 -1.24088432 -0.10922482  0.00903452  0.05932512
  0.0332726  -0.06385303 -0.21387098 -0.38816279 -0.55158806 -1.46637985
 -1.31169408 -0.13806368  0.01715044  0.10032913  0.10470919  0.03728335
 -0.08248402 -0.22559627 -0.35774913 -1.24332559 -1.30844891 -0.08866675
  0.10347531  0.21555348  0.24274549  0.1941531   0.09095905 -0.03696953
 -0.15559362 -1.03077091 -1.22232798  0.04184847  0.26488758  0.39616412
  0.43345636  0.38865093  0.28532158  0.1548752   0.03176534 -0.85063035
 -1.05047936  0.2501329   0.49220965  0.62786623  0.65842627  0.59945813
  0.4

In [6]:
u = np.linalg.solve(A, B.reshape(-1, 1))

n = len(x)-1
u0 = np.zeros(n**2)
for i in range(1, n+1):
    for j in range(1, n+1):
        u0[get_pos(n, i, j)] = sol(x[i]+dx/2, y[j]+dy/2)
print(np.linalg.norm(u-u0))
print(u)

2.8021797900891914e+18
[[2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.80217979e+16]
 [2.8